SELECT m.id AS expected_module_id
FROM (
  SELECT 'D1.1' AS id UNION ALL SELECT 'D1.2' UNION ALL SELECT 'D1.3' UNION ALL SELECT 'D1.4' UNION ALL
  SELECT 'D2.1' UNION ALL SELECT 'D2.2' UNION ALL SELECT 'D2.3' UNION ALL
  SELECT 'F1.1' UNION ALL SELECT 'F1.2' UNION ALL
  SELECT 'L1.1' UNION ALL SELECT 'L1.2' UNION ALL SELECT 'L1.3' UNION ALL
  SELECT 'L2.1' UNION ALL SELECT 'L2.2' UNION ALL
  SELECT 'L3.1' UNION ALL SELECT 'L3.2' UNION ALL SELECT 'L3.3' UNION ALL
  SELECT 'T1.1' UNION ALL SELECT 'T1.2' UNION ALL SELECT 'T1.3' UNION ALL
  SELECT 'T2.1' UNION ALL SELECT 'T2.2' UNION ALL SELECT 'T2.3' UNION ALL SELECT 'T2.4' UNION ALL
  SELECT 'T3.1' UNION ALL SELECT 'T3.2' UNION ALL SELECT 'T3.3'
) AS m
LEFT JOIN modules ON modules.id = m.id
WHERE modules.id IS NULL;
